from odoo import models, fields

class ClinicFlowAIAudit(models.Model):
    _name = 'clinicflow.ai.audit'
    _description = 'ClinicFlow AI Service Audit Trail'
    _order = 'generated_at desc'

    visit_id = fields.Many2one(
        'clinicflow.visit', 
        string="Linked Visit", 
        ondelete='cascade', 
        index=True
    )
    provider = fields.Char(string="AI Provider", required=True)
    task_type = fields.Selection([
        ('soap', 'SOAP Note Generation'),
        ('discharge', 'Discharge Note Generation'),
        ('owner_instructions', 'Owner Instructions'),
        ('referral', 'Referral Letter')
    ], string="Task Type", required=True)
    
    generated_at = fields.Datetime(string="Generated At", default=fields.Datetime.now, required=True)
    generated_by = fields.Many2one('res.users', string="Generated By", default=lambda self: self.env.user, required=True)
    approved_by = fields.Many2one('res.users', string="Approved By")
    
    prompt_hash = fields.Char(string="Prompt Hash ID")
    response_hash = fields.Char(string="Response Hash ID")
    tokens = fields.Integer(string="Tokens Used", default=0)
    cost = fields.Float(string="Estimated Cost ($)", digits=(16, 6), default=0.0)
