from . import pet
from . import visit
from . import vaccination
from . import prescription
from . import admission
from . import timeline_event
from . import weight_record
from . import account_move
from . import partner
from . import calendar_event
from . import dashboard
